import { ThermostatReading } from "../models/thermostat-reading.model";
import { _thermostats } from "../_mockdata/thermostats.mock";

export let _thermostat_readings: ThermostatReading[] = [
  {
    ID: 1001,
    thermostat: _thermostats[0],
    temperature: 22,
    humidity: 38,
    battery_charge: 33,
  },
  {
    ID: 1000,
    thermostat: _thermostats[0],
    temperature: 23,
    humidity: 39,
    battery_charge: 34,
  },
  {
    ID: 210,
    thermostat: _thermostats[0],
    temperature: 24,
    humidity: 39,
    battery_charge: 35,
  },
  {
    ID: 209,
    thermostat: _thermostats[0],
    temperature: 23,
    humidity: 38,
    battery_charge: 36,
  },
  {
    ID: 208,
    thermostat: _thermostats[0],
    temperature: 21,
    humidity: 38,
    battery_charge: 55,
  },
  {
    ID: 207,
    thermostat: _thermostats[0],
    temperature: 15,
    humidity: 26,
    battery_charge: 49,
  },
  {
    ID: 206,
    thermostat: _thermostats[0],
    temperature: 15,
    humidity: 26,
    battery_charge: 49,
  },
  {
    ID: 205,
    thermostat: _thermostats[0],
    temperature: 15,
    humidity: 26,
    battery_charge: 49,
  },
  {
    ID: 204,
    thermostat: _thermostats[0],
    temperature: 15,
    humidity: 26,
    battery_charge: 49,
  },
  {
    ID: 203,
    thermostat: _thermostats[0],
    temperature: 15,
    humidity: 26,
    battery_charge: 49,
  },
  {
    ID: 202,
    thermostat: _thermostats[0],
    temperature: 23,
    humidity: 39,
    battery_charge: 34,
  },
  {
    ID: 201,
    thermostat: _thermostats[0],
    temperature: 24,
    humidity: 39,
    battery_charge: 35,
  },
  {
    ID: 1002,
    thermostat: _thermostats[1],
    temperature: 21,
    humidity: 36,
    battery_charge: 55,
  },
  {
    ID: 216,
    thermostat: _thermostats[1],
    temperature: 14,
    humidity: 64,
    battery_charge: 45,
  },
  {
    ID: 215,
    thermostat: _thermostats[1],
    temperature: 14,
    humidity: 64,
    battery_charge: 45,
  },
  {
    ID: 214,
    thermostat: _thermostats[1],
    temperature: 14,
    humidity: 64,
    battery_charge: 45,
  },
  {
    ID: 213,
    thermostat: _thermostats[1],
    temperature: 14,
    humidity: 64,
    battery_charge: 45,
  },
  {
    ID: 212,
    thermostat: _thermostats[1],
    temperature: 14,
    humidity: 64,
    battery_charge: 45,
  },
  {
    ID: 211,
    thermostat: _thermostats[1],
    temperature: 14,
    humidity: 64,
    battery_charge: 45,
  },
  {
    ID: 1003,
    thermostat: _thermostats[2],
    temperature: 20,
    humidity: 44,
    battery_charge: 87,
  },
  {
    ID: 1004,
    thermostat: _thermostats[3],
    temperature: 26,
    humidity: 41,
    battery_charge: 98,
  },
  {
    ID: 1005,
    thermostat: _thermostats[4],
    temperature: 18,
    humidity: 30,
    battery_charge: 10,
  },
  {
    ID: 1006,
    thermostat: _thermostats[5],
    temperature: 28,
    humidity: 45,
    battery_charge: 48,
  },
  {
    ID: 1007,
    thermostat: _thermostats[6],
    temperature: 20,
    humidity: 24,
    battery_charge: 68,
  },
];
